server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio-service?useTimeZone=True&severTimeZone=UTC
    username: root
    password: mysql112
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #properties:
     # hibernate:
       #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/cambio-service?useTimeZone=True&severTimeZone=UTC
    user: root
    password: mysql112
springdoc:
  api-docs:
    path: /cambio-service/v3/api-docs